### ISSUE TITLE
Caniuse-lite is outdated. Please run:   npx update-browserslist-db@latest

### ISSUE THREAD

**Issue by Pragrammist** [lustre-labs/dev-tools#82]
I ran into an unexpected issue while trying to bundle your project with esbuild.
Here's the error message I got:

    Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme

Rebuilding...
ReferenceError: plugin is not defined
    at C:\Users\f\Documents\gleam_project\me_and_others\front_ui\tailwind.config.js:11:12
    at evalModule (C:\snapshot\tailwindcss\node_modules\jiti\dist\jiti.js:1:255614)
    at jiti (C:\snapshot\tailwindcss\node_modules\jiti\dist\jiti.js:1:253542)
    at C:\snapshot\tailwindcss\lib\lib\load-config.js:48:30
    at loadConfig (C:\snapshot\tailwindcss\lib\lib\load-config.js:50:6)
    at Object.loadConfig (C:\snapshot\tailwindcss\lib\cli\build\plugin.js:135:49)
    at Object.getContext (C:\snapshot\tailwindcss\lib\cli\build\plugin.js:204:27)
    at C:\snapshot\tailwindcss\lib\cli\build\plugin.js:254:38
    at C:\snapshot\tailwindcss\lib\processTailwindFeatures.js:48:11
    at Object.Once (C:\snapshot\tailwindcss\lib\cli\build\plugin.js:262:19).

My tailwind config file
```js
/** @type {import('tailwindcss').Config} */
const plugin = require('tailwindcss/plugin');
const flattenColorPalette = require('tailwindcss/lib/util/flattenColorPalette').default;

module.exports = {
  content: ["./index.html", "./src/**/*.{gleam,mjs}"],
  theme: {
    extend: {
      width: {
        '256': '64rem',
        '158': '39.5rem'
      }
    },
  },
  plugins: [
    plugin(function({ matchUtilities, theme }) {
      matchUtilities(
        {
          'stop-color': (value) => ({
            stopColor: value
          }),
        },
        { values: flattenColorPalette(theme('colors')), type: 'color' }
      )
    })
  ],
};
```

**Comment by Pragrammist** [comment]
I tried npx update-browserslist-db@latest

**Comment by Pragrammist** [comment]
Removing of plugin solve the problem, but i need this plugin
